feat: Add srsran_init.sh and qos.yml to srsRAN ConfigMap

diff --git a/helm/srsran/templates/gnb.yaml b/helm/srsran/templates/gnb.yaml
--- a/helm/srsran/templates/gnb.yaml
+++ b/helm/srsran/templates/gnb.yaml
@@ -3,15 +3,35 @@ kind: ConfigMap
 metadata:
   name: srsran-gnb-config
 data:
+  srsran_init.sh: |
+    #!/bin/bash
+    export IP_ADDR=$(awk 'END{print $1}' /etc/hosts)
+    mkdir -p /etc/srsran
+    if [[ -z "$COMPONENT_NAME" ]]; then
+      echo "Error: COMPONENT_NAME environment variable not set"; exit 1;
+    elif [[ "$COMPONENT_NAME" =~ ^(gnb[[:digit:]]*$) ]]; then
+      echo "Configuring component: $COMPONENT_NAME"
+      cp /mnt/srsran/${COMPONENT_NAME}.yml /etc/srsran/gnb.yml
+    else
+      echo "Error: Invalid component name: $COMPONENT_NAME"
+    fi
+    cp /mnt/srsran/qos.yml /etc/srsran/qos.yml
+    sed -i "s|PLMN|${MCC}${MNC}|g" /etc/srsran/gnb.yml
+    sed -i "s|AMF_IP|${AMF_IP}|g" /etc/srsran/gnb.yml
+    sed -i "s|SRS_GNB_IP|${SRS_GNB_IP}|g" /etc/srsran/gnb.yml
+    sed -i "s|TAC|${TAC}|g" /etc/srsran/gnb.yml
+    service dbus start && service avahi-daemon start
+    cd /mnt/srsran
+    exec gnb -c /etc/srsran/gnb.yml -c /etc/srsran/qos.yml
   gnb.yml: |
     cu_cp:
       amf:
-        addr: 10.100.50.249
-        bind_addr: 0.0.0.0
+        addr: AMF_IP
+        bind_addr: SRS_GNB_IP
         supported_tracking_areas:
-          - tac: 1
+          - tac: TAC
             plmn_list:
-              - plmn: "20893"
+              - plmn: "PLMN"
                 tai_slice_support_list:
                   - sst: 1
     ru_sdr:
@@ -25,12 +45,39 @@ data:
       band: 78
       channel_bandwidth_MHz: 20
       common_scs: 30
-      plmn: "20893"
-      tac: 1
+      plmn: "PLMN"
+      tac: TAC
       pci: 1
     log:
       filename: /tmp/gnb.log
       all_level: warning
+  qos.yml: |
+    qos:
+      - five_qi: 9
+        pdcp:
+          tx:
+            sn: 18
+            discard_timer: -1
+            status_report_required: false
+          rx:
+            sn: 18
+            t_reordering: 220
+            out_of_order_delivery: false
+        rlc:
+          mode: am
+          am:
+            tx:
+              sn: 18
+              t-poll-retransmit: 100
+              max-retx-threshold: 32
+              poll-pdu: 16
+              poll-byte: -1
+              queue-size: 16384
+              queue-bytes: 6172672
+            rx:
+              sn: 18
+              t-reassembly: 20
+              t-status-prohibit: 10
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -59,14 +106,24 @@ spec:
         env:
         - name: COMPONENT_NAME
           value: gnb
+        - name: MCC
+          value: "208"
+        - name: MNC
+          value: "93"
+        - name: AMF_IP
+          value: "10.100.50.249"
+        - name: SRS_GNB_IP
+          value: "0.0.0.0"
+        - name: TAC
+          value: "1"
         volumeMounts:
-        - name: gnb-config
-          mountPath: /mnt/srsran/gnb.yml
-          subPath: gnb.yml
+        - name: srsran-config
+          mountPath: /mnt/srsran
       volumes:
-      - name: gnb-config
+      - name: srsran-config
         configMap:
           name: srsran-gnb-config
+          defaultMode: 0755
 ---
 apiVersion: v1
 kind: Service
